steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: probot-app-release-notes
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: probot-app-release-notes
    agents:
      queue: workers
  - name: ':jest:'
    command: yarn jest
    plugins:
      'docker-compose#v1.7.0':
        run: probot-app-release-notes
    agents:
      queue: workers
